#!/bin/bash
#
#       /etc/rc.d/init.d/zabbix_agentd
#
# Starts the zabbix_agentd daemon
#
# chkconfig: - 95 5
# description: Zabbix Monitoring Agent
# processname: zabbix_agentd
# pidfile: /tmp/zabbix_agentd.pid

# Modified for Zabbix 2.0.0
# May 2012, Zabbix SIA

# Source function library.

#. /etc/init.d/functions

RETVAL=0
prog="Zabbix Agent"
ZABBIX_BIN="/opt/zabbix/sbin/zabbix_agentd"
ZABBIX_CONF=/opt/zabbix/conf/zabbix_agentd.conf
mkdir -p /opt/zabbix/var/lock/subsys/

if [ ! -x ${ZABBIX_BIN} ] ; then
        echo -n "${ZABBIX_BIN} not installed! "
        # Tell the user this has skipped
        exit 5
fi

start() {
        echo -n $"Starting $prog: "
        $ZABBIX_BIN -c $ZABBIX_CONF
        RETVAL=$?
        [ $RETVAL -eq 0 ] && touch /opt/zabbix/var/lock/subsys/zabbix_agentd
        echo
}

stop() {
        echo -n $"Stopping $prog: "
        killprocs
	RETVAL=$?
        [ $RETVAL -eq 0 ] && rm -f /opt/zabbix/var/lock/subsys/zabbix_agentd
        echo
}
killprocs(){
        ps -ef | grep $ZABBIX_BIN | awk '$1=="zabbix"{print $2}' | xargs kill >/dev/null 2>&1        
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  reload|restart)
        stop
        sleep 10
        start
        RETVAL=$?
        ;;
  condrestart)
        if [ -f /opt/zabbix/var/lock/subsys/zabbix_agentd ]; then
            stop
            start
        fi
        ;;
  status)
        status $ZABBIX_BIN
        RETVAL=$?
        ;;
  *)
        echo $"Usage: $0 {condrestart|start|stop|restart|reload|status}"
        exit 1
esac

exit $RETVAL
