httpd:
    image: httpd
    container_name: httpd
    volumes:
        - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        - /home/kk/containers/httpd/conf:/usr/local/apache2/conf:ro
        - /home/kk/containers/httpd/htdocs:/usr/local/apache2/htdocs
        - /home/kk/containers/httpd/ssl:/usr/local/apache2/ssl:ro
    ports:
        - "80:80"
        - "443:443"

nginx:
    image: nginx
    container_name: nginx
    volumes:
        - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        - /home/kk/containers/nginx/nginx:/etc/nginx:ro
        - /home/kk/containers/nginx/html:/usr/share/nginx/html:ro
    ports:
        - "80:80"
        - "443:443"

tomcat:
    image: tomcat:7-jre7
    container_name: tomcat
    volumes:
        - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        - /home/kk/containers/tomcat/conf:/usr/local/tomcat/conf
        - /home/kk/containers/tomcat/cert:/usr/local/tomcat/cert:ro
        - /home/kk/containers/tomcat/webapps:/usr/local/tomcat/webapps:ro
    ports:
        - "8080:8080"
        - "8443:8443"

mariadb:
    image: mariadb
    container_name: mariadb
    environment:
        - MYSQL_ROOT_PASSWORD="1xaUvCpfPANkM"
        - character-set-server=utf8mb4
        - collation-server=utf8mb4_unicode_ci
        - log-bin
        - binlog-format=MIXED
        - server_id=1
    volumes:
        - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        - /var/lib/mysql:/var/lib/mysql
    ports:
        - "3306:3306"
#
# logstash:
#         image: docker.elastic.co/logstash/logstash:6.4.2
#         container_name: logstash
#         volumes:
#                 - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
#

oracle:
   image: sath89/oracle-ee-11g
   container_name: oracle
   environment:
       - CHARACTER_SET=AL32UTF8
       - DEFAULT_SYS_PASS=oracle
       - processes=1000
       - sessions=1105
       - transactions=1215
   ports:
       - 1521:1521
   volumes:
       - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
       - /etc/localtime:/etc/localtime:ro
       # restore datafile using 
       - ./containers/oracle_env:/u01/app/oracle
       - ./containers/oracle_env/dockerfile/.bash_profile:/home/oracle/.bash_profile:ro
       - ./containers/oracle_env/dockerfile/libncurses.so.6.1:/lib64/libncurses.so.6:ro
       - ./containers/oracle_env/dockerfile/libreadline.so.7.0:/lib64/libreadline.so.7:ro
       - ./containers/oracle_env/dockerfile/rlwrap:/usr/bin/rlwrap:ro
       - ./containers/oracle_env/dockerfile/login.sql:/home/oracle/login.sql:ro
       - ./containers/oracle_env/dockerfile/oracle_archive_backup.sh:/home/oracle/oracle_archive_backup.sh:ro
       - ./containers/oracle_env/dockerfile/oracle_full_backup.sh:/home/oracle/oracle_full_backup.sh:ro
       - ./containers/oracle_env/dockerfile/rman_arch:/home/oracle/rman_arch:ro
       - ./containers/oracle_env/dockerfile/rman_full:/home/oracle/rman_full:ro
